git rev-parse --abbrev-ref HEADversion: 2
jobs:
  build:
    docker:
      - image: node:8

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: 
          name: "Check changes folders"
          command: |
            for folder in `git log --format="" --name-only ${CIRCLE_COMPARE_URL##http*/} | cut -d"/" -f1 | sort -u`; do
             echo "contents in $folder were modified"
             #this would be a call to specific testing, etc on changed directory
            done