version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.5

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Setup npm
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: 
          name: "Configuring git"
          command: |
            git config --global user.email "ln.munhoz@gmail.com"
            git config --global user.name "lnmunhoz"

      - run: 
          name: "Install base Dependencies"
          command: |
            yarn install

      - run:
          name: "Install projects dependencies"
          command: |
            yarn install-all

      - run:
          name: "Check for changes on packages/common-a and build"
          command: |
            COMMIT_RANGE=$(echo $CIRCLE_COMPARE_URL | sed 's:^.*/compare/::g')
            if [[ $(git diff $COMMIT_RANGE --name-only | grep "packages/common-a") != "" ]]; then
              cd packages/common-a
              yarn test
            else
              echo "No changes detected..."
            fi
            cd ../../
      
      - run:
          name: "Check for changes on projects/node-app and build"
          command: |
            COMMIT_RANGE=$(echo $CIRCLE_COMPARE_URL | sed 's:^.*/compare/::g')
            if [[ $(git diff $COMMIT_RANGE --name-only | grep "projects/node-app") != "" ]]; then
              cd projects/node-app
              yarn build
              yarn test
            else
              echo "No changes detected..."
            fi
            cd ../../
      - run:
          name: "Publish"
          command: |
            yarn publish-all