version: 2
jobs:
  build:
    docker:
      - image: node:8

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: 
          name: "Configuring git"
          command: |
            git config --global user.email "ln.munhoz@gmail.com"
            git config --global user.name "lnmunhoz"

      - run: 
          name: "Install Lerna"
          command: |
            yarn global add lerna

      - run:
          name: "Install all dependencies"
          command: |
            lerna bootstrap
      
      - run:
          name: "Check for changes on projects/node-app and build"
          command: |
            COMMIT_RANGE=$(echo $CIRCLE_COMPARE_URL | sed 's:^.*/compare/::g')
            if [[ $(git diff $COMMIT_RANGE --name-only | grep "projects/node-app") != "" ]]; then
              cd projects/node-app
              yarn build
              yarn test
            else
              echo "No changes detected..."
            fi
            cd ../../
      - run:
          name: "Publish"
          command: |
            yarn publish-all